PCG-CLI build and readme

diff --git a/.github/workflows/pcgcli-main.yml b/.github/workflows/pcgcli-main.yml
--- a/.github/workflows/pcgcli-main.yml
+++ b/.github/workflows/pcgcli-main.yml
@@ -26,17 +26,29 @@ jobs:
           chmod +x gradlew && ./gradlew clean test uberJar
       - name: Build with Maven
         run: mvn clean package
-      - name: Validate Gradle Executable Jar was created
+      - name: Validate artifacts were created
         run: |
-          FILE_PATH="build/libs/cg.jar"
+          FILE_PATH="build/cg.jar"
           if [ -f "$FILE_PATH" ]; then
             echo "Validation successful: $FILE_PATH was created."
           else
             echo "Validation failed: $FILE_PATH was not found."
             exit 1 # Fails the workflow step
           fi
-      - name: Validate Maven Executable Jar was created
-        run: |
+          FILE_PATH="build/cg.zip"
+          if [ -f "$FILE_PATH" ]; then
+            echo "Validation successful: $FILE_PATH was created."
+          else
+            echo "Validation failed: $FILE_PATH was not found."
+            exit 1 # Fails the workflow step
+          fi
+          FILE_PATH="build/libs/cg.tar"
+          if [ -f "$FILE_PATH" ]; then
+            echo "Validation successful: $FILE_PATH was created."
+          else
+            echo "Validation failed: $FILE_PATH was not found."
+            exit 1 # Fails the workflow step
+          fi
           FILE_PATH="target/cg.jar"
           if [ -f "$FILE_PATH" ]; then
             echo "Validation successful: $FILE_PATH was created."
